'use client'
import './globals.css'

import { useState } from 'react'
import { Inter } from 'next/font/google'
import Navigation from './ui/Navigation'
import Footer from './ui/Footer'
import Sidebar from './ui/Sidebar'
import AboveF from './aboveFooter/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children })
 {
  const [isOpen, setIsOpen] = useState(false)

  const toggleSidebar= () => {
    setIsOpen(!isOpen)
  }

  return (
    <html lang="en">
      <body className={inter.className}>
       <Navigation toggleSidebar={toggleSidebar}/>
       <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar}/>
        {children}
        <AboveF />
       <Footer /> 
      </body>
    </html>
  )
}
